# ***MTZ INC***

In [4]:
# IMPORTANDO AS BIBLIOTECAS

import numpy as np
import pandas as pd

In [5]:
# LENDO O ARQUIVO "mtz_exemplo.txt"

matriz = pd.read_fwf('mtz_exemplo.txt')
print("Matriz do arquivo:\n",matriz)

Matriz do arquivo:
    0  1  1.1  1.2  1.3
0  0  0    1    1    1
1  1  1    0    0    0
2  1  1    0    1    1


In [7]:
# RETIRANDO O HEADER E O INDEX DA MATRIZ

mtz_sem_header = pd.DataFrame(np.array(matriz))
print("Matriz sem o header:\n",mtz_sem_header)

mtz_sem_index = mtz_sem_header.drop(columns=[0])
print("\n\nMatriz sem o index:\n",mtz_sem_index)

Matriz sem o header:
    0  1  2  3  4
0  0  0  1  1  1
1  1  1  0  0  0
2  1  1  0  1  1


Matriz sem o index:
    1  2  3  4
0  0  1  1  1
1  1  0  0  0
2  1  0  1  1


In [8]:
# TRANSFORMANDO EM ARRAY PARA UTILIZAR DEPOIS

array_da_mtz = np.array(mtz_sem_index)
print("Array da matriz:\n",array_da_mtz)

Array da matriz:
 [[0 1 1 1]
 [1 0 0 0]
 [1 0 1 1]]


In [ ]:
# MATRIZ INCIDENCIA

mtz_incidencia = pd.DataFrame(array_da_mtz, index=['v1','v2','v3','v4'],  columns=['x','y','z','w','k'])
print("Matriz Incidencia:\n",mtz_incidencia)

Matriz Incidencia:
     x  y  z  w  k
v1  0  1  1  1  1
v2  0  0  1  1  1
v3  1  1  0  0  0
v4  1  1  0  1  1


# ***MTZ SM***

In [ ]:
# MATRIZ SIMILARIDADE

matriz_similaridade = np.dot(array_da_mtz, array_da_mtz.T)
#                                                       |> MATRIZ TRANSPOSTA

df_similaridade = pd.DataFrame(matriz_similaridade, index=['V1', 'V2', 'V3', 'V4'],  columns=['V1', 'V2', 'V3', 'V4'])

print("Matriz de Similaridade:")
print(df_similaridade)

Matriz de Similaridade:
   V1 V2 V3 V4
V1  4  3  1  3
V2  3  3  0  2
V3  1  0  2  2
V4  3  2  2  4


# **MTZ COO**

In [ ]:
# MATRIZ DE COOCORRENCIA

matriz_coocorrencia = np.dot(array_da_mtz.T, array_da_mtz)

df_coocorrencia = pd.DataFrame(matriz_coocorrencia, index=['x','y','z','w','k'],  columns=['x','y','z','w','k'])

print("Matriz de Coocorrencia:")
print(df_coocorrencia)

Matriz de Coocorrencia:
   x  y  z  w  k
x  2  2  0  1  1
y  2  3  1  2  2
z  0  1  2  2  2
w  1  2  2  3  3
k  1  2  2  3  3
