#Operações de matrizes



In [1]:
import numpy as np

#Construção de Matrizes



In [2]:
#construção de matrizes

matriz = np.arange(1,10)

print(matriz)

[1 2 3 4 5 6 7 8 9]


In [3]:
print(type(matriz))

<class 'numpy.ndarray'>


In [4]:
#construção utilizando vetores

#utilizando listas

a = [1,3,5,7]
b = [9,11,13,15]

matriz = [a,b]

print(matriz) #2x4

[[1, 3, 5, 7], [9, 11, 13, 15]]


In [5]:
a = [1,2,3,4]

matriz = [a]
print(matriz)
print(type(matriz))

[[1, 2, 3, 4]]
<class 'list'>


In [6]:
#utilizando tuplas(imutáveis)

a = (1,3,5,7)
b = (9,11,13,15)

matriz = (a,b)

print(matriz)

((1, 3, 5, 7), (9, 11, 13, 15))


In [7]:
a = (1,2,3,4,'a','b','c',True,False,1.4,1.9)

matriz = (a)
print(matriz)
print(type(matriz))

(1, 2, 3, 4, 'a', 'b', 'c', True, False, 1.4, 1.9)
<class 'tuple'>


In [8]:
#construção por linhas e colunas

matriz = np.arange(5,11).reshape((3, 2))

print(matriz)

[[ 5  6]
 [ 7  8]
 [ 9 10]]


#Manipulação de elementos

In [9]:
#manipulação de elementos (substituição de elementos)

matriz = np.arange(6)

print(matriz)

[0 1 2 3 4 5]


In [10]:
matriz[2] = 10
print(matriz)

[ 0  1 10  3  4  5]


In [11]:
a = [1,2,3,4]
a[2] = 10
matriz = [a]
print(matriz)

[[1, 2, 10, 4]]


In [12]:
# tupla
a = (1,2,3,4)
a[2] = 10
matriz = (a)
print(matriz)

TypeError: 'tuple' object does not support item assignment

In [13]:
matriz = np.arange(6).reshape((3, 2))

print(matriz)

[[0 1]
 [2 3]
 [4 5]]


In [14]:
matriz[1][1] = 10
print(matriz)

[[ 0  1]
 [ 2 10]
 [ 4  5]]


#Operações entre matrizes


In [18]:
matriz_1 = np.arange(9).reshape((3,3))

print(matriz_1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
matriz_2 = np.arange(9).reshape((3,3))

print(matriz_2)
print(type(matriz_2))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
<class 'numpy.ndarray'>


In [19]:
#soma

matriz_1 = np.array(matriz_1)
matriz_2 = np.array(matriz_2)

matriz_soma = matriz_1 + matriz_2

print(matriz_soma)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [20]:
#subtração

matriz_1 = np.array(matriz_1)
matriz_2 = np.array(matriz_2)

matriz_sub = matriz_1 - matriz_2
print(matriz_sub)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [21]:
#multiplicação por Constante(k)

matriz_k = matriz_1 * 5
print(matriz_k)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]


#Multiplicação de Matriz

In [22]:
matriz_multi_1 = [1,3,2],[2,1,1] #matriz 2x3
print(matriz_multi_1)

([1, 3, 2], [2, 1, 1])


In [23]:
matriz_multi_2 = [2,1,3],[1,0,2],[1,1,0] #matriz 3x3
print(matriz_multi_2)

([2, 1, 3], [1, 0, 2], [1, 1, 0])


In [24]:
matriz_multi_1 = np.array(matriz_multi_1)
matriz_multi_2 = np.array(matriz_multi_2)

matriz_multi = matriz_multi_1 @ matriz_multi_2

print(matriz_multi) #matriz 2x3

[[7 3 9]
 [6 3 8]]


#Calculos extras

In [25]:
#determinante

matriz = np.arange(1,10).reshape(3, 3)
determinante = np.linalg.det(matriz)

print(matriz)
print('\n')
print(determinante)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


0.0


In [26]:
#dimensão

matriz = np.arange(9).reshape(3, 3)

print(matriz)
print('\n')
print(matriz.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


(3, 3)


In [27]:
#extração de diagonal

matriz = np.arange(9).reshape(3, 3)
diagonal = np.diagonal(matriz)

print(matriz)
print('\n')
print(diagonal)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[0 4 8]


In [28]:
#juntar matrizes por linhas (empilhamento vertical)
matriz_1 = np.arange(1,10).reshape(3,3)

print(matriz_1)
print('\n')

matriz_2 = np.arange(10,19).reshape(3,3)

print(matriz_2)
print('\n')

matriz = np.vstack((matriz_1,matriz_2))

print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[10 11 12]
 [13 14 15]
 [16 17 18]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [29]:
#juntar matrizes por colunas (empilhamento horizontal)

matriz_1 = np.arange(1,10).reshape(3,3)

print(matriz_1)
print('\n')

matriz_2 = np.arange(10,19).reshape(3,3)

print(matriz_2)
print('\n')

matriz = np.hstack((matriz_1,matriz_2))

print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[10 11 12]
 [13 14 15]
 [16 17 18]]


[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
